### ISSUE TITLE
Location permission

### ISSUE THREAD

**Issue by araobp** [araobp/sensor-network-android#2]
```
08-13 00:31:54.439 5919-5939/jp.araobp.iot.cli E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
                                                                 Process: jp.araobp.iot.cli, PID: 5919
                                                                 java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
                                                                     at android.os.Parcel.readException(Parcel.java:1942)
                                                                     at android.os.Parcel.readException(Parcel.java:1888)
                                                                     at com.google.android.gms.internal.zzed.zza(Unknown Source:10)
                                                                     at com.google.android.gms.internal.zzcda.zzdv(Unknown Source:9)
                                                                     at com.google.android.gms.internal.zzcdd.getLastLocation(Unknown Source:19)
                                                                     at com.google.android.gms.internal.zzcdj.getLastLocation(Unknown Source:2)
                                                                     at com.google.android.gms.location.zze.zza(Unknown Source:2)
                                                                     at com.google.android.gms.internal.zzbaq.zza(Unknown Source:8)
                                                                     at com.google.android.gms.internal.zzbdd.zzb(Unknown Source:9)
                                                                     at com.google.android.gms.internal.zzbdd.zza(Unknown Source:17)
                                                                     at com.google.android.gms.internal.zzbdb.handleMessage(Unknown Source:273)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by araobp** [comment]
Requires an explicit permission request to the location service.

**Comment by araobp** [comment]
fixed
